sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t mehrtest01/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mehrtest01/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-test'
  env: 'Dockertest-env'
  bucket_name: 'elasticbeanstalk-us-east-2-895135776690'
  bucket_path: 'docker-test'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
